import "./globals.css";
import { Barlow_Semi_Condensed } from "next/font/google";

const Barlow_600 = Barlow_Semi_Condensed({
  subsets: ["latin"],
  display: "swap",
  weight: "600",
  variable: "--Barlow-600",
});
const Barlow_700 = Barlow_Semi_Condensed({
  subsets: ["latin"],
  display: "swap",
  weight: "600",
  variable: "--Barlow-700",
});
const Barlow_300 = Barlow_Semi_Condensed({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
  variable: "--Barlow-300",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${Barlow_300.variable} ${Barlow_600.variable} ${Barlow_700.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
